import { MaterialCommunityIcons, FontAwesome5, Entypo, Ionicons, Feather } from '@expo/vector-icons';

export const SliderOPtions = [
  {
    id: 1,
    title: 'Latest',
    Icon: (props) => <Ionicons name="globe-outline" {...props} />,
  },
  {
    id: 2,
    title: 'Hotels',
    Icon: (props) => <Ionicons name="bed-outline" {...props} />,
  },
  {
    id: 3,
    title: 'Resorts',
    Icon: (props) => <MaterialCommunityIcons name="beach" {...props} />,
  },
  {
    id: 4,
    title: 'Villas',
    Icon: (props) => <MaterialCommunityIcons name="home-city-outline" {...props} />,
  },
  {
    id: 5,
    title: 'Islands',
    Icon: (props) => <MaterialCommunityIcons name="island" {...props} />,
  },
  {
    id: 6,
    title: 'Farms',
    Icon: (props) => <MaterialCommunityIcons name="home-flood" {...props} />,
  },
  {
    id: 7,
    title: 'Hubs',
    Icon: (props) => <MaterialCommunityIcons name="office-building" {...props} />,
  },
];


export const fullFlights = [
  {
    id: 'AI2975',
    airline: {
      name: 'Air India',
      logo: 'https://nextgentrip.com/images/AI.gif',
    },
    flightNumber: '2975',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T05:55:00',
      terminal: '3',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T08:20:00',
      terminal: '2',
    },
    duration: '2h 25m',
    price: 5757,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3-3 Layout',
    meals: 'Complimentary Meals',
    amenities: ['Standard Recliner (31" Legroom)', 'Power and USB Available'],
    date: '2025-05-31',
  },
  {
    id: '6E101',
    airline: {
      name: 'IndiGo',
      logo: 'https://nextgentrip.com/images/6E.gif',
    },
    flightNumber: '6E101',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T06:30:00',
      terminal: '2',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T08:50:00',
      terminal: '1',
    },
    duration: '2h 20m',
    price: 5641,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Buy on Board',
    amenities: ['Power Outlet'],
    date: '2025-05-31',
  },
  {
    id: 'SG421',
    airline: {
      name: 'SpiceJet',
      logo: 'https://res.cloudinary.com/wego/f_auto,fl_lossy,w_1000,q_auto/v1480072078/flights/airlines_square/QP',
    },
    flightNumber: 'SG421',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T07:15:00',
      terminal: '1D',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T09:35:00',
      terminal: '2',
    },
    duration: '2h 20m',
    price: 5599,
    baggage: 'Adult',
    checkIn: '20 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Buy on Board',
    amenities: ['USB Charging', 'Recliner Seats'],
    date: '2025-05-31',
  },
  {
    id: 'UK933',
    airline: {
      name: 'Vistara',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bd/Vistara_Logo.svg/1200px-Vistara_Logo.svg.png',
    },
    flightNumber: 'UK933',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T09:00:00',
      terminal: '3',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T11:25:00',
      terminal: '2',
    },
    duration: '2h 25m',
    price: 5999,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Complimentary Meals',
    amenities: ['Power and USB', 'Wi-Fi Enabled'],
    date: '2025-05-31',
  },
  {
    id: 'QP135',
    airline: {
      name: 'Akasa Air',
      logo: 'https://res.cloudinary.com/wego/f_auto,fl_lossy,w_1000,q_auto/v1480072078/flights/airlines_square/QP',
    },
    flightNumber: 'QP135',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T10:20:00',
      terminal: '2',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T12:50:00',
      terminal: '1',
    },
    duration: '2h 30m',
    price: 5480,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Buy on Board',
    amenities: ['USB Charging'],
    date: '2025-05-31',
  },
  {
    id: 'AI850',
    airline: {
      name: 'Air India',
      logo: 'https://nextgentrip.com/images/AI.gif',
    },
    flightNumber: '850',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T12:00:00',
      terminal: '3',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T14:25:00',
      terminal: '2',
    },
    duration: '2h 25m',
    price: 5890,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3-3 Layout',
    meals: 'Complimentary Meals',
    amenities: ['Power and USB Available'],
    date: '2025-05-31',
  },
  {
    id: '6E205',
    airline: {
      name: 'IndiGo',
      logo: 'https://nextgentrip.com/images/6E.gif',
    },
    flightNumber: '6E205',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T13:45:00',
      terminal: '1',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T16:10:00',
      terminal: '1',
    },
    duration: '2h 25m',
    price: 5720,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Buy on Board',
    amenities: ['Wi-Fi Available'],
    date: '2025-05-31',
  },
  {
    id: 'SG889',
    airline: {
      name: 'SpiceJet',
      logo: 'https://res.cloudinary.com/wego/f_auto,fl_lossy,w_1000,q_auto/v1480072078/flights/airlines_square/QP',
    },
    flightNumber: '889',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T15:30:00',
      terminal: '1D',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T17:55:00',
      terminal: '2',
    },
    duration: '2h 25m',
    price: 5620,
    baggage: 'Adult',
    checkIn: '20 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Buy on Board',
    amenities: ['USB Charging'],
    date: '2025-05-31',
  },
  {
    id: 'UK981',
    airline: {
      name: 'Vistara',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bd/Vistara_Logo.svg/1200px-Vistara_Logo.svg.png',
    },
    flightNumber: 'UK981',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T17:10:00',
      terminal: '3',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T19:35:00',
      terminal: '2',
    },
    duration: '2h 25m',
    price: 6070,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Complimentary Meals',
    amenities: ['Power Outlet', 'USB', 'Wi-Fi'],
    date: '2025-05-31',
  },
  {
    id: 'QP221',
    airline: {
      name: 'Akasa Air',
      logo: 'https://res.cloudinary.com/wego/f_auto,fl_lossy,w_1000,q_auto/v1480072078/flights/airlines_square/QP',
    },
    flightNumber: '221',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T20:00:00',
      terminal: '2',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T22:25:00',
      terminal: '1',
    },
    duration: '2h 25m',
    price: 5530,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Buy on Board',
    amenities: ['USB Charging'],
    date: '2025-05-31',
  }
];
export const packagess =[
  {
    "name": "Romantic Europe Getaway",
    "location": "Paris, Venice, Lucerne",
    "duration": "9 Nights / 10 Days",
    "type": "Honeymoon Package",
    "price": "₹1,00,000",
    "description": "Explore the romance of Europe with candlelight dinners, Eiffel Tower visit, gondola ride in Venice, and scenic Swiss Alps.",
    "image": "https://www.wapititravel.com/blog/wp-content/uploads/2020/06/Venice_Italy.jpg",
    "activities": ["Eiffel Tower", "Gondola Ride", "Swiss Alps Tour", "Wine Tasting"]
  },
  {
    "name": "Spiritual Varanasi Retreat",
    "location": "Varanasi, India",
    "duration": "3 Nights / 4 Days",
    "type": "Pilgrimage Package",
    "price": "₹8,500",
    "description": "Immerse yourself in the spirituality of Varanasi with guided temple visits, Ganga aarti, and boat rides at dawn.",
    "image": "https://www.travelzonevaranasi.com/sites/default/files/imagenodes/large/Varansi.jpg",
    "activities": ["Kashi Vishwanath Temple", "Ganga Aarti", "Boat Ride", "Sarnath Tour"]
  },
  {
    "name": "Kerala Ayurveda Rejuvenation",
    "location": "Munnar, Alleppey, Kovalam",
    "duration": "6 Nights / 7 Days",
    "type": "Ayurveda Package",
    "price": "₹22,000",
    "description": "Relax with traditional Ayurvedic therapies, backwater houseboat stays, and wellness cuisine.",
    "image": "https://media1.thrillophilia.com/filestore/330j1qdk2shkzvymsagpujnwk97d_shutterstock_377921479.jpg?ar=16%3A9&w=400&dpr=2",
    "activities": ["Ayurvedic Massage", "Backwater Cruise", "Yoga", "Tea Plantation Tour"]
  },
  {
    "name": "Manali Adventure Thrill",
    "location": "Manali, India",
    "duration": "5 Nights / 6 Days",
    "type": "Adventure Package",
    "price": "₹14,000",
    "description": "Experience snow activities, trekking, and river rafting in the scenic hills of Himachal.",
    "image": "https://media.assettype.com/outlooktraveller%2F2023-11%2Fcadcbaf8-a8c0-413c-b896-ae56724d3c1d%2Fshutterstock_1653595066.jpg",
    "activities": ["Paragliding", "Trekking", "River Rafting", "Snowboarding"]
  },
  {
    "name": "Goa Leisure Escape",
    "location": "Goa, India",
    "duration": "4 Nights / 5 Days",
    "type": "Leisure Package",
    "price": "₹9,999",
    "description": "Relax on sun-kissed beaches, enjoy vibrant nightlife, and explore Goan cuisine.",
    "image": "https://3.imimg.com/data3/RU/MX/MY-7516435/goa-beachs.jpg",
    "activities": ["Beach Hopping", "Casino Night", "Sunset Cruise", "Fort Aguada Visit"]
  },
  {
    "name": "Thailand Group Fiesta",
    "location": "Bangkok, Pattaya",
    "duration": "6 Nights / 7 Days",
    "type": "Group Departure Package",
    "price": "₹32,500",
    "description": "Enjoy buzzing city life, coral islands, and shopping with a group of fellow travelers.",
    "image": "https://www.flamingotravels.co.in/_next/image?url=https%3A%2F%2Fimgcdn.flamingotravels.co.in%2FImages%2FCity%2FBangkok-City-tour-With-Lunch-2.jpg&w=3840&q=90",
    "activities": ["Coral Island Tour", "Alcazar Show", "Floating Market", "Street Food Tour"]
  },
  {
    "name": "Mystical Leh-Ladakh Expedition",
    "location": "Leh, Nubra, Pangong",
    "duration": "7 Nights / 8 Days",
    "type": "Adventure Package",
    "price": "₹26,000",
    "description": "Conquer high-altitude passes, explore monasteries, and camp by the Pangong Lake.",
    "image": "https://www.lehladakhtourism.com/ladakh-packages/images/nubra-pangong/ladakh1.jpg",
    "activities": ["Khardung La Pass", "Camel Safari", "Lake Camping", "Monastery Tour"]
  },
  {
    "name": "Rajasthan Royal Heritage Tour",
    "location": "Jaipur, Jodhpur, Udaipur",
    "duration": "5 Nights / 6 Days",
    "type": "Family Package",
    "price": "₹17,500",
    "description": "Explore majestic palaces, forts, cultural shows, and local markets of royal Rajasthan.",
    "image": "https://pmlholidays.com/admin/production/images/blogs/Best-Places-to-visit-in-Rajasthan%20compress.jpg",
    "activities": ["City Palace", "Desert Safari", "Light & Sound Show", "Shopping Bazaar"]
  },
  {
    "name": "South India Temple Circuit",
    "location": "Madurai, Rameshwaram, Kanyakumari",
    "duration": "6 Nights / 7 Days",
    "type": "Pilgrimage Package",
    "price": "₹15,500",
    "description": "Visit famous temples and spiritual landmarks in Tamil Nadu and Kerala.",
    "image": "https://www.epicyatra.com/wp-content/uploads/2023/05/main-qimg-5565f3379d32605e33f0994ef95c2c68-lq.webp",
    "activities": ["Meenakshi Temple", "Vivekananda Rock", "Ramanathaswamy Temple", "Sunrise View"]
  },
  {
    "name": "Andaman Island Escape",
    "location": "Port Blair, Havelock Island",
    "duration": "5 Nights / 6 Days",
    "type": "Leisure Package",
    "price": "₹20,000",
    "description": "Dive into pristine beaches, crystal clear waters, and underwater adventures.",
    "image": "https://www.india.com/wp-content/uploads/2019/10/Andaman-Nicobar.jpg",
    "activities": ["Snorkeling", "Scuba Diving", "Beach Relaxation", "Cellular Jail Visit"]
  }
]


export const cruiseOfferCard = [
  {
    id: 1,
    title: "Mesmerizing Ocean Views",
    description: "Witness captivating horizons, golden sunsets, and stunning coastal landscapes that will leave you enchanted.",
    price: 40000,
    image: "https://images.pexels.com/photos/813011/pexels-photo-813011.jpeg",
    button: "Explore"
  },
  {
    id: 2,
    title: "Ultimate Luxury on Board",
    description: "Experience world-class amenities, gourmet dining, and unmatched service in the lap of oceanic luxury.",
    price: 55000,
    image: "https://www.cruises.com/images/web/44/1263/shp/ship_sm.jpg",
    button: "Explore"
  },
  {
    id: 3,
    title: "Tropical Island Escape",
    description: "Cruise through turquoise waters to discover secluded beaches and lush tropical islands.",
    price: 48000,
    image: "https://www.cruzely.com/wp-content/uploads/icon-aft-sm.jpg",
    button: "Explore"
  },
  {
    id: 4,
    title: "Mediterranean Marvels",
    description: "Sail along the Mediterranean coast and explore historic cities, azure waters, and ancient wonders.",
    price: 60000,
    image: "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/870/420/75/vision-dam/digital/parks-platform/parks-global-assets/disney-cruise-line/ships/destiny/overview/O_sh01_fr1420_x2_v3-Bow-v2-2x1.jpg?2024-07-25T18:09:00+00:00",
    button: "Explore"
  },
  {
    id: 5,
    title: "Arctic Expedition Voyage",
    description: "Embark on an adventurous cruise to witness glaciers, polar wildlife, and the Northern Lights.",
    price: 85000,
    image: "https://t3.ftcdn.net/jpg/01/49/80/00/360_F_149800067_6TzchoMIijIG7y241uQexxzWROibrGuo.jpg",
    button: "Explore"
  },
  {
    id: 6,
    title: "Romantic Sunset Sail",
    description: "Perfect for couples—enjoy candlelit dinners, serene waters, and magical sunset backdrops.",
    price: 38000,
    image: "https://static.toiimg.com/thumb/103573944/cruise.jpg?width=1200&height=900",
    button: "Explore"
  }
];

export const cruiseDestinations = [
  {
    id: 1,
    title: 'UK Cruise',
    flag: '🇬🇧',
    image: 'https://img.etimg.com/thumb/width-1200,height-1200,imgsize-158410,resizemode-75,msid-110265744/magazines/panache/is-anand-mahindra-planning-to-launch-a-luxury-cruise-ship-tycoon-drops-pic-of-worlds-largest-cruise-vessel-triggering-speculations.jpg',
  },
  {
    id: 2,
    title: 'Europe Cruise',
    flag: '🇪🇺',
    image: 'https://static.wixstatic.com/media/2cd8ac_9f3bdaa0e7014bb4aa11bf3ed89bdee7~mv2.jpg/v1/fill/w_640,h_390,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/2cd8ac_9f3bdaa0e7014bb4aa11bf3ed89bdee7~mv2.jpg',
  },
  {
    id: 3,
    title: 'Italy Cruise',
    flag: '🇮🇹',
    image: 'https://cruisefever.net/wp-content/uploads/2025/04/wonderoftheseascruiseship.jpg',
  },
  {
    id: 4,
    title: 'Spain Cruise',
    flag: '🇪🇸',
    image: 'https://etimg.etb2bimg.com/photo/117475809.cms',
  },
  {
    id: 5,
    title: 'China Cruise',
    flag: '🇨🇳',
    image: 'https://marinedc.com/media/bilder/referansegalleri/midnatsol1.png',
  },
  {
    id: 6,
    title: 'Korea Cruise',
    flag: '🇰🇷',
    image: 'https://s3.amazonaws.com/cms.ipressroom.com/412/files/202504/67eea6123d6332920e37f52c_Sunsation+Point+Aerial+Rendering/Sunsation+Point+Aerial+Rendering_social.jpg',
  },
];


export const busTrips = [
  {
    id: 'bus1',
    name: 'Volvo Deluxe AC',
    price: 1500,
    from: 'Delhi',
    to: 'Agra',
    durationHours: 4,
    busType: 'Semi-Sleeper',
    seatsAvailable: 12,
    amenities: ['Water Bottle', 'Charging Port', 'Blanket', 'Pillow', 'CCTV'],
    routes: [
      { stop: 'Delhi', time: '06:00 AM' },
      { stop: 'Ghaziabad', time: '06:30 AM' },
      { stop: 'Bulandshahr', time: '07:30 AM' },
      { stop: 'Hathras', time: '08:30 AM' },
      { stop: 'Mathura', time: '09:00 AM' },
      { stop: 'Agra', time: '10:00 AM' },
    ],
    rating: 4.5,
  },
  {
    id: 'bus2',
    name: 'Mercedes AC Sleeper',
    price: 2200,
    from: 'Mumbai',
    to: 'Pune',
    durationHours: 6,
    busType: 'Sleeper',
    seatsAvailable: 8,
    amenities: ['Water Bottle', 'Blanket', 'Charging Port', 'Bed Sheet', 'Pillow'],
    routes: [
      { stop: 'Mumbai', time: '09:00 PM' },
      { stop: 'Thane', time: '09:30 PM' },
      { stop: 'Kalyan', time: '10:00 PM' },
      { stop: 'Lonavala', time: '11:30 PM' },
      { stop: 'Pune', time: '01:00 AM' },
    ],
    rating: 4.7,
  },
  {
    id: 'bus3',
    name: 'Non-AC Deluxe Seater',
    price: 800,
    from: 'Chennai',
    to: 'Bangalore',
    durationHours: 7,
    busType: 'Seater',
    seatsAvailable: 20,
    amenities: ['Water Bottle', 'Charging Port', 'CCTV'],
    routes: [
      { stop: 'Chennai', time: '07:00 AM' },
      { stop: 'Kanchipuram', time: '07:45 AM' },
      { stop: 'Vellore', time: '08:30 AM' },
      { stop: 'Krishnagiri', time: '10:00 AM' },
      { stop: 'Hosur', time: '11:15 AM' },
      { stop: 'Bangalore', time: '02:00 PM' },
    ],
    rating: 4.1,
  },
  {
    id: 'bus4',
    name: 'Volvo AC Seater',
    price: 1300,
    from: 'Hyderabad',
    to: 'Vijayawada',
    durationHours: 5,
    busType: 'Seater',
    seatsAvailable: 15,
    amenities: ['Water Bottle', 'Charging Port', 'Blanket', 'Pillow'],
    routes: [
      { stop: 'Hyderabad', time: '08:00 AM' },
      { stop: 'Nalgonda', time: '09:00 AM' },
      { stop: 'Suryapet', time: '10:30 AM' },
      { stop: 'Kodad', time: '11:15 AM' },
      { stop: 'Vijayawada', time: '01:00 PM' },
    ],
    rating: 4.3,
  },
  {
    id: 'bus5',
    name: 'Scania AC Sleeper',
    price: 1800,
    from: 'Kolkata',
    to: 'Durgapur',
    durationHours: 6,
    busType: 'Sleeper',
    seatsAvailable: 10,
    amenities: ['Water Bottle', 'Charging Port', 'Blanket', 'CCTV', 'Bed Sheet', 'Pillow'],
    routes: [
      { stop: 'Kolkata', time: '07:30 AM' },
      { stop: 'Howrah', time: '07:45 AM' },
      { stop: 'Burdwan', time: '09:30 AM' },
      { stop: 'Durgapur', time: '01:00 PM' },
    ],
    rating: 4.6,
  },
  {
    id: 'bus6',
    name: 'Tata AC Semi-Sleeper',
    price: 1100,
    from: 'Jaipur',
    to: 'Udaipur',
    durationHours: 6,
    busType: 'Semi-Sleeper',
    seatsAvailable: 14,
    amenities: ['Water Bottle', 'Charging Port', 'Blanket', 'Pillow'],
    routes: [
      { stop: 'Jaipur', time: '06:00 AM' },
      { stop: 'Ajmer', time: '07:30 AM' },
      { stop: 'Nathdwara', time: '09:30 AM' },
      { stop: 'Udaipur', time: '12:00 PM' },
    ],
    rating: 4.2,
  },
];
