import { MaterialCommunityIcons, FontAwesome5, Entypo, Ionicons, Feather } from '@expo/vector-icons';

export const SliderOPtions = [
  {
    id: 1,
    title: 'Latest',
    Icon: (props) => <Ionicons name="globe-outline" {...props} />,
  },
  {
    id: 2,
    title: 'Hotels',
    Icon: (props) => <Ionicons name="bed-outline" {...props} />,
  },
  {
    id: 3,
    title: 'Resorts',
    Icon: (props) => <MaterialCommunityIcons name="beach" {...props} />,
  },
  {
    id: 4,
    title: 'Villas',
    Icon: (props) => <MaterialCommunityIcons name="home-city-outline" {...props} />,
  },
  {
    id: 5,
    title: 'Islands',
    Icon: (props) => <MaterialCommunityIcons name="island" {...props} />,
  },
  {
    id: 6,
    title: 'Farms',
    Icon: (props) => <MaterialCommunityIcons name="home-flood" {...props} />,
  },
  {
    id: 7,
    title: 'Hubs',
    Icon: (props) => <MaterialCommunityIcons name="office-building" {...props} />,
  },
];


export const fullFlights = [
  {
    id: 'AI2975',
    airline: {
      name: 'Air India',
      logo: 'https://nextgentrip.com/images/AI.gif',
    },
    flightNumber: '2975',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T05:55:00',
      terminal: '3',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T08:20:00',
      terminal: '2',
    },
    duration: '2h 25m',
    price: 5757,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3-3 Layout',
    meals: 'Complimentary Meals',
    amenities: ['Standard Recliner (31" Legroom)', 'Power and USB Available'],
    date: '2025-05-31',
  },
  {
    id: '6E101',
    airline: {
      name: 'IndiGo',
      logo: 'https://nextgentrip.com/images/6E.gif',
    },
    flightNumber: '6E101',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T06:30:00',
      terminal: '2',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T08:50:00',
      terminal: '1',
    },
    duration: '2h 20m',
    price: 5641,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Buy on Board',
    amenities: ['Power Outlet'],
    date: '2025-05-31',
  },
  {
    id: 'SG421',
    airline: {
      name: 'SpiceJet',
      logo: 'https://res.cloudinary.com/wego/f_auto,fl_lossy,w_1000,q_auto/v1480072078/flights/airlines_square/QP',
    },
    flightNumber: 'SG421',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T07:15:00',
      terminal: '1D',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T09:35:00',
      terminal: '2',
    },
    duration: '2h 20m',
    price: 5599,
    baggage: 'Adult',
    checkIn: '20 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Buy on Board',
    amenities: ['USB Charging', 'Recliner Seats'],
    date: '2025-05-31',
  },
  {
    id: 'UK933',
    airline: {
      name: 'Vistara',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bd/Vistara_Logo.svg/1200px-Vistara_Logo.svg.png',
    },
    flightNumber: 'UK933',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T09:00:00',
      terminal: '3',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T11:25:00',
      terminal: '2',
    },
    duration: '2h 25m',
    price: 5999,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Complimentary Meals',
    amenities: ['Power and USB', 'Wi-Fi Enabled'],
    date: '2025-05-31',
  },
  {
    id: 'QP135',
    airline: {
      name: 'Akasa Air',
      logo: 'https://res.cloudinary.com/wego/f_auto,fl_lossy,w_1000,q_auto/v1480072078/flights/airlines_square/QP',
    },
    flightNumber: 'QP135',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T10:20:00',
      terminal: '2',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T12:50:00',
      terminal: '1',
    },
    duration: '2h 30m',
    price: 5480,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Buy on Board',
    amenities: ['USB Charging'],
    date: '2025-05-31',
  },
  {
    id: 'AI850',
    airline: {
      name: 'Air India',
      logo: 'https://nextgentrip.com/images/AI.gif',
    },
    flightNumber: '850',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T12:00:00',
      terminal: '3',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T14:25:00',
      terminal: '2',
    },
    duration: '2h 25m',
    price: 5890,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3-3 Layout',
    meals: 'Complimentary Meals',
    amenities: ['Power and USB Available'],
    date: '2025-05-31',
  },
  {
    id: '6E205',
    airline: {
      name: 'IndiGo',
      logo: 'https://nextgentrip.com/images/6E.gif',
    },
    flightNumber: '6E205',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T13:45:00',
      terminal: '1',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T16:10:00',
      terminal: '1',
    },
    duration: '2h 25m',
    price: 5720,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Buy on Board',
    amenities: ['Wi-Fi Available'],
    date: '2025-05-31',
  },
  {
    id: 'SG889',
    airline: {
      name: 'SpiceJet',
      logo: 'https://res.cloudinary.com/wego/f_auto,fl_lossy,w_1000,q_auto/v1480072078/flights/airlines_square/QP',
    },
    flightNumber: '889',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T15:30:00',
      terminal: '1D',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T17:55:00',
      terminal: '2',
    },
    duration: '2h 25m',
    price: 5620,
    baggage: 'Adult',
    checkIn: '20 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Buy on Board',
    amenities: ['USB Charging'],
    date: '2025-05-31',
  },
  {
    id: 'UK981',
    airline: {
      name: 'Vistara',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bd/Vistara_Logo.svg/1200px-Vistara_Logo.svg.png',
    },
    flightNumber: 'UK981',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T17:10:00',
      terminal: '3',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T19:35:00',
      terminal: '2',
    },
    duration: '2h 25m',
    price: 6070,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Complimentary Meals',
    amenities: ['Power Outlet', 'USB', 'Wi-Fi'],
    date: '2025-05-31',
  },
  {
    id: 'QP221',
    airline: {
      name: 'Akasa Air',
      logo: 'https://res.cloudinary.com/wego/f_auto,fl_lossy,w_1000,q_auto/v1480072078/flights/airlines_square/QP',
    },
    flightNumber: '221',
    from: {
      city: 'Delhi',
      code: 'DEL',
      time: '2025-05-31T20:00:00',
      terminal: '2',
    },
    to: {
      city: 'Mumbai',
      code: 'BOM',
      time: '2025-05-31T22:25:00',
      terminal: '1',
    },
    duration: '2h 25m',
    price: 5530,
    baggage: 'Adult',
    checkIn: '15 KG',
    cabin: 'Included',
    seatLayout: '3-3 Layout',
    meals: 'Buy on Board',
    amenities: ['USB Charging'],
    date: '2025-05-31',
  }
];
